// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Cadastracar.DATA.Models
{
    public partial class CADASTRACARContext : DbContext
    {
        public CADASTRACARContext()
        {
        }

        public CADASTRACARContext(DbContextOptions<CADASTRACARContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
        public virtual DbSet<VwVeiculo> VwVeiculo { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-3CJ07US;Initial Catalog=CADASTRACAR;User ID=sa;Password=tub2019");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Categoria>(entity =>
            {
                entity.HasKey(e => e.CtgaCodigo)
                    .HasName("PK__CATEGORI__19E904CC87BDBC9C");

                entity.Property(e => e.CtgaDescricao).IsUnicode(false);
            });

            modelBuilder.Entity<Funcionario>(entity =>
            {
                entity.HasKey(e => e.FuncCodigo)
                    .HasName("PK__FUNCIONA__5771D13307940A10");

                entity.HasIndex(e => e.Cpf)
                    .HasName("UQ__FUNCIONA__C1F89731146628A3")
                    .IsUnique();

                entity.Property(e => e.Cpf).IsUnicode(false);

                entity.Property(e => e.FuncNome).IsUnicode(false);
            });

            modelBuilder.Entity<Veiculo>(entity =>
            {
                entity.HasKey(e => e.VcoCodigo)
                    .HasName("PK__VEICULO__CDEFFF0C9CA3AFC1");

                entity.HasIndex(e => e.VcoFrota)
                    .HasName("UQ__VEICULO__9C65B222DA885E70")
                    .IsUnique();

                entity.HasIndex(e => e.VcoPlaca)
                    .HasName("UQ__VEICULO__94CF1CC32EB047BC")
                    .IsUnique();

                entity.Property(e => e.VcoFrota).IsUnicode(false);

                entity.Property(e => e.VcoPlaca).IsUnicode(false);

                entity.HasOne(d => d.VcoCodCategoriaNavigation)
                    .WithMany(p => p.Veiculo)
                    .HasForeignKey(d => d.VcoCodCategoria)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CategoriaVeiculo");

                entity.HasOne(d => d.VcoCodFuncResponsavelNavigation)
                    .WithMany(p => p.Veiculo)
                    .HasForeignKey(d => d.VcoCodFuncResponsavel)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_FuncionarioVeiculo");
            });

            modelBuilder.Entity<VwVeiculo>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VW_VEICULO");

                entity.Property(e => e.CtgaDescricao).IsUnicode(false);

                entity.Property(e => e.FuncNome).IsUnicode(false);

                entity.Property(e => e.VcoFrota).IsUnicode(false);

                entity.Property(e => e.VcoPlaca).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}