// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cadastracar.DATA.Models
{
    [Table("CATEGORIA")]
    public partial class Categoria
    {
        public Categoria()
        {
            Veiculo = new HashSet<Veiculo>();
        }

        [Key]
        [DisplayName("Identificação")]
        public int CtgaCodigo { get; set; }
        [Required(ErrorMessage = "A descrição é obrigatória")]
        [StringLength(50)]
        [DisplayName("Descrição")]
        public string CtgaDescricao { get; set; }

        [InverseProperty("VcoCodCategoriaNavigation")]
        public virtual ICollection<Veiculo> Veiculo { get; set; }
    }
}