// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cadastracar.DATA.Models
{
    [Table("FUNCIONARIO")]
    public partial class Funcionario
    {
        public Funcionario()
        {
            Veiculo = new HashSet<Veiculo>();
        }

        [Key]
        [DisplayName("Identificação")]
        public int FuncCodigo { get; set; }
        [Required(ErrorMessage = "O nome do funcionário é obrigatório")]
        [StringLength(200)]
        [DisplayName("Nome")]
        public string FuncNome { get; set; }
        [Required(ErrorMessage = "CPF é obrigatório")]
        [Column("CPF")]
        [StringLength(14)]
        [DisplayName("CPF")]
        public string Cpf { get; set; }

        [InverseProperty("VcoCodFuncResponsavelNavigation")]
        public virtual ICollection<Veiculo> Veiculo { get; set; }
    }
}