// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cadastracar.DATA.Models
{
    [Table("VEICULO")]
    public partial class Veiculo
    {
        [Key]
        public int VcoCodigo { get; set; }
        [Required(ErrorMessage = "A placa do veículo é obrigatória")]
        [StringLength(8)]
        [DisplayName("Placa")]
        public string VcoPlaca { get; set; }
        [Required(ErrorMessage = "A frota do veículo é obrigatória")]
        [StringLength(50)]
        [DisplayName("Frota")]
        public string VcoFrota { get; set; }
        [Required(ErrorMessage = "O ano de modelo do veículo é obrigatório")]
        [DisplayName("Ano de modelo")]
        public int VcoAnoModelo { get; set; }
        [Required(ErrorMessage = "O ano de fabricação do veículo é obrigatório")]
        [DisplayName("Ano de fabricação")]
        public int VcoAnoFabricacao { get; set; }
        [Column(TypeName = "datetime")]
        [Required(ErrorMessage = "A data de aquisição do veículo é obrigatória")]
        [DisplayName("Data aquisição")]
        public DateTime VcoDataAquisicao { get; set; }
        [Required]
        public int VcoCodFuncResponsavel { get; set; }
        [Required]
        public int VcoCodCategoria { get; set; }

        [ForeignKey(nameof(VcoCodCategoria))]
        [InverseProperty(nameof(Categoria.Veiculo))]
        public virtual Categoria VcoCodCategoriaNavigation { get; set; }
        [ForeignKey(nameof(VcoCodFuncResponsavel))]
        [InverseProperty(nameof(Funcionario.Veiculo))]
        public virtual Funcionario VcoCodFuncResponsavelNavigation { get; set; }
    }
}