// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cadastracar.DATA.Models
{
    public partial class VwVeiculo
    {
        [DisplayName("Identificação")]
        public int VcoCodigo { get; set; }
        [Required]
        [StringLength(8)]
        [DisplayName("Placa")]
        public string VcoPlaca { get; set; }
        [Required]
        [StringLength(50)]
        [DisplayName("Frota")]
        public string VcoFrota { get; set; }
        [DisplayName("Ano de modelo")]
        public int VcoAnoModelo { get; set; }
        [DisplayName("Ano de fabricação")]
        public int VcoAnoFabricacao { get; set; }
        [Column(TypeName = "datetime")]
        [DisplayName("Data de aquisição")]
        public DateTime VcoDataAquisicao { get; set; }
        public int VcoCodFuncResponsavel { get; set; }
        public int VcoCodCategoria { get; set; }
        [Required]
        [StringLength(50)]
        [DisplayName("Categoria")]
        public string CtgaDescricao { get; set; }
        public int FuncCodigo { get; set; }
        [Required]
        [StringLength(200)]
        [DisplayName("Nome do responsável")]
        public string FuncNome { get; set; }
    }
}